### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-ColecoVision#1]
Some overlays contain transparent / translucent pixels outside the desired area.

Here the list:

Brain Strainers (USA, Europe).png
Buck Rogers - Planet of Zoom (USA, Europe).png
Bump 'N' Jump (USA, Europe).png
BurgerTime (USA, Europe).png
Cabbage Patch Kids - Adventures in the Park (USA, Europe).png
Cabbage Patch Kids Picture Show (USA, Europe).png
Campaign '84 (USA).png
Carnival (USA, Europe).png
Choplifter (USA, Europe).png
Chuck Norris - Super Kicks (USA).png
Congo Bongo (USA, Europe).png
Donkey Kong Jr (USA, Europe).png
Evolution (USA).png
Facemaker (USA).png
Fathom (USA).png
Flipper Slipper (USA).png
Fortune Builder (USA, Europe).png
Fraction Fever (USA).png
Frantic Freddy (USA).png
From Out of the Jungle - Tarzan (USA).png
Frontline (USA, Europe).png
Jungle Hunt (USA).png
Keystone Kapers (USA).png
Lady Bug (USA, Europe).png
Learning with Leeper (USA).png
Linking Logic (USA).png
Logic Levels (USA).png
Looping (USA, Europe).png
M.A.S.H (Europe).png
Memory Manor (USA).png
Meteoric Shower (USA).png
Monkey Academy (USA, Europe).png
Montezuma's Revenge (USA).png
Moonsweeper (USA).png
Motocross Racer (USA).png
Mountain King (USA).png
Mousetrap (USA, Europe).png
Mr. Do! (USA, Europe).png
Nova Blast (USA).png
Oil's Well (USA).png
Omega Race (USA, Europe).png
One on One (USA).png
Rocky Super-Action Boxing (USA, Europe).png
Sammy Lightfoot (USA).png
Sector Alpha (USA).png
Sewer Sam (USA).png
Sir Lancelot (USA).png
Skiing (USA).png
Slither (USA).png
Slurpy (USA).png
Smurf Paint 'n Play Workshop (USA, Europe).png
Smurf Rescue (USA, Europe).png
Space Fury (USA, Europe).png
Space Panic (USA, Europe).png
Spectron (USA).png
Spy Hunter (USA, Europe).png
Squish 'Em Sam! (USA).png
Star Trek (USA, Europe).png
Star Wars (USA).png
Strike It! (USA).png
Subroc (USA, Europe).png
Super Action Baseball (USA, Europe).png
Super Action Football (USA, Europe).png
Super Action Soccer (USA, Europe).png
Super Cobra (USA).png

Here you can see the specific areas that have pixels outside the desired area.

https://drive.google.com/file/d/1fp1uSHq_LOBfZ9YjfoeHLtuEQRG5gpNV/view?usp=sharing

**Comment by thebezelproject** [comment]
Files have been updated.

**Comment by toniosj** [comment]
Artillery Duel (USA).png

There are blank pixels on left & right borders.
