### ISSUE TITLE
Blank pixels on borders

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-ColecoVision#2]
Almost all overlays have transparent pixels on the left and right sides.

Examples:

Boulder Dash (USA).png
Artillery Duel (USA).png
Centipede (USA).png
.......

![unknown](https://user-images.githubusercontent.com/20826760/77212053-1684d000-6b06-11ea-866f-aa588c57a5ba.png)

**Comment by thebezelproject** [comment]
Updated edges on all files.

**Comment by toniosj** [comment]
There are still transparent pixels.

![pixels](https://user-images.githubusercontent.com/20826760/77224706-993e7700-6b68-11ea-9bda-941aacf60389.png)
![pixels2](https://user-images.githubusercontent.com/20826760/77224708-9d6a9480-6b68-11ea-92da-2e52c64e4b7b.png)
![pixels3](https://user-images.githubusercontent.com/20826760/77224709-9fccee80-6b68-11ea-86ec-8a851085da0b.png)
