### ISSUE TITLE
Transparent pixles in almost all overlays

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-ColecoVision#3]
There are still transparent pixels in almost all overlays

Exemples:

![pixels](https://user-images.githubusercontent.com/20826760/77224706-993e7700-6b68-11ea-9bda-941aacf60389.png)
![pixels2](https://user-images.githubusercontent.com/20826760/77224708-9d6a9480-6b68-11ea-92da-2e52c64e4b7b.png)
![pixels3](https://user-images.githubusercontent.com/20826760/77224709-9fccee80-6b68-11ea-86ec-8a851085da0b.png)

**Comment by thebezelproject** [comment]
Reworked all files.
